name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get dependencies
        run: sudo apt install libcurl4-openssl-dev

      - name: cmake
        run: cmake .;

      - name: Build
        run: make

      - name: Run tests
        run: make test